DROP TABLE LOCATION;
DROP TYPE POINT;
CREATE TYPE POINT AS OBJECT (X NUMBER, Y NUMBER);
.
/
CREATE TABLE LOCATION (
  NAME   VARCHAR2(80),
  ORIGIN POINT
);
INSERT INTO LOCATION VALUES ( 'Someplace', POINT(11,17) );
COMMIT;
